***Reasons for Including Each Dataset***

**Hypothesis:**
I believe there may be a correlation between the tax gap and rising income over time in the UK.

**Dataset 1** — HMRC Measuring Tax Gaps (Primary Dataset)
Source:  HM Revenue & Customs — GOV.UK
File: Measuring_tax_gap_online_tables_2025.xlsx
URL: https://www.gov.uk/government/statistics/measuring-tax-gaps-tables

**Reason for inclusion:**
This is the primary metric under investigation. The tax gap measures the difference between the tax theoretically owed and the amount actually collected. It is HMRC’s own headline compliance indicator, published annually since 2005–06. Over the 19-year series it has declined from 7.4% of theoretical liabilities in 2005–06 to 5.3% in 2023–24, making it a clear and well-sourced ‘changing value’ for our purposes.


**Dataset 2** — ONS Annual Survey of Hours and Earnings (ASHE)
Source:  Office for National Statistics — ONS Website
File: selectedestimates19972025.xlsx
URL: https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/ashe1997to2015selectedestimates

**Reason for inclusion:**
ASHE provides the UK’s most comprehensive and consistent annual series of employee earnings, running from 1997 to 2025.

**Licence and restrictions:**
Open Government Licence v3.0 (OGL v3.0) for both datasets. Free to copy, adapt, and use commercially or non-commercially. Required attribution: “Contains public sector information licensed under the Open Government Licence v3.0.” No restrictions on storage or analysis.

**UK GDPR:**
Not applicable. All figures are aggregated national estimates. No individual-level, identifiable, or special-category data is present.

***Dashboard Insights***

**What the axes show** 
Each dot is one year. Its horizontal position (x-axis) is that year's median annual earnings, and its vertical position (y-axis) is the total tax gap in £bn. So dots further right = higher wages, dots further up = bigger tax gap.

**The overall trend** The dots form a rough upward slope from left to right — as earnings have grown over time, the tax gap has also generally grown. 2023 and 2024 sit at the top right, with both the highest wages and the biggest tax gap (around £46-47bn).

**The colour (Income YoY %)** 
The colour scale shows how fast income grew that year. Yellow/orange dots (2022, 2023, 2024) had fast income growth — those are the post-COVID years where wages surged. Dark purple dots (2010, 2012) had near-zero or negative income growth — the austerity years after the 2008 financial crisis.

**Outliers:**
*2020 sits unusually high for its earnings level — the tax gap spiked during COVID despite wages barely moving, likely due to disrupted tax collection
*2010 is the lowest dot overall — earnings actually fell slightly that year (dark purple) and the tax gap was at its smallest
*2014 appears above the trend line — the tax gap jumped to £36.5bn while earnings were still relatively modest at £22k

**Conclusion** 
There is a loose correlation that requires further research. Earnings and the tax gap have broadly risen together, but the tax gap has accelerated sharply since 2022 while income growth, though faster, hasn't kept pace.

In [1]:
import pandas as pd

In [2]:
%pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

Importing the two datasets

In [3]:
# Adjust the path if your username is different
income_raw = pd.read_excel('/Users/alexandruvasile/Desktop/selectedestimates19972025.xlsx',
    sheet_name="Table 1",   # All employees pay
    header=None             # Headers to be handled manually
)

# Preview the raw data to see its structure
income_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,Table 1,"Alla employees' pay and paid hours by sex, Uni...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,1997.00,1998.00,1999.00,2000.00,2001.00,2002.00,2003.00,2004 exc.,...,2018.00,2019.00,2020.00,2021.0,NaN,2021Soc20,2022.00,2023.0,2024.00,2025
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,All,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Median gross annual earnings (£)b,NaN,NaN,NaN,14888.00,15800.00,16438.00,16964.00,17508.00,18128,...,24003.00,24937.00,25886.00,25971.0,NaN,25990,27774.00,29511.0,31600.00,32890
7,Percentage annual increase,NaN,NaN,NaN,NaN,6.10,4.00,3.20,3.20,3.5,...,2.20,3.90,3.80,0.3,NaN,0,6.90,6.3,7.10,4.1
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Median gross weekly earnings (£),NaN,268.90,280.20,290.00,299.60,312.50,324.80,334.80,349.6,...,460.00,479.10,479.10,504.4,NaN,505.1,533.70,574.9,613.50,642.5
10,Percentage annual increase,NaN,NaN,4.20,3.50,3.30,4.30,4.00,3.10,4.4,...,2.60,4.20,0.00,5.3,NaN,0,5.70,7.7,6.70,4.7
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Median hourly earnings (£),NaN,7.07,7.36,7.66,7.93,8.28,8.62,8.95,9.35,...,12.77,13.28,13.71,14.1,NaN,14.12,14.79,16.0,17.09,17.96
13,Percentage annual increase,NaN,NaN,4.10,4.00,3.50,4.40,4.10,3.80,4.5,...,2.40,4.00,3.30,2.8,NaN,0,4.70,8.2,6.80,5.1
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
taxgap_raw = pd.read_excel(
    '/Users/alexandruvasile/Desktop/Measuring_tax_gap_online_tables_2025.xlsx',
    sheet_name=  "Table 1.3",   # Tax gap in £ billion by type of tax
    header=None
)

# Preview
taxgap_raw.head(10)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,Table 1.3: Tax gap (in £ billion) by type of tax,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,This worksheet contains 1 table.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,This table contains detailed notes: [note 3][n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Estimates are rounded to the nearest £0.1 bill...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tax,Type,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,...,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20,2020-21,2021-22,2022-23,2023-24
5,VAT,Total VAT,11.6,9.8,9.0,12.5,9.7,9.3,11.4,12.0,...,11.5,10.9,11.4,11.2,9.7,12.0,7.0,8.4,13.1,8.9
6,Excise duty,Tobacco duty,2.2,2.1,1.7,1.9,1.8,1.4,1.5,1.7,...,1.2,1.8,1.9,1.5,1.6,1.6,1.7,1.7,1.6,1.4
7,Excise duty,Beer duty,0.3,0.4,0.3,0.3,0.4,0.4,0.4,0.5,...,0.6,0.6,0.6,0.5,0.7,0.7,0.7,0.5,0.4,0.7
8,Excise duty,Spirits duties,0.2,0.3,0.1,0.3,0.1,0.1,0.1,0.1,...,0.3,0.2,0.1,0.2,0.1,0.1,0.1,0.1,0.1,0.1
9,Excise duty,Hydrocarbon oils duty,0.7,0.7,0.6,0.8,0.7,0.4,0.2,0.1,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,<0.1,<0.1

--- INCOME DATA CLEANING ---

Step 1: Pull out the year row (row index 2) and earnings row (row index 6)

In [5]:
year_row      = income_raw.iloc[2]   # e.g. 1997, 1998, ... 2025
earnings_row  = income_raw.iloc[6]   # median gross annual earnings values

Step 2: Build a small dataframe from those two rows

In [6]:
income_df = pd.DataFrame({
    'year':     year_row.values,
    'median_annual_earnings_gbp': earnings_row.values
})

Step 3: Drop rows where the year is not a plain number

In [7]:
# (removes NaNs, "2004 exc.", "2021Soc20" duplicates etc.)
income_df = income_df[pd.to_numeric(income_df['year'], errors='coerce').notna()]

Step 4: Convert year to integer and earnings to float

In [8]:
income_df['year'] = income_df['year'].astype(int)
income_df['median_annual_earnings_gbp'] = pd.to_numeric(
    income_df['median_annual_earnings_gbp'], errors='coerce'
)

Step 5: Drop any remaining rows with no earnings value

In [9]:
income_df = income_df.dropna(subset=['median_annual_earnings_gbp'])

Step 6: If any year appears twice (due to methodology breaks), keep the last one

In [10]:
income_df = income_df.drop_duplicates(subset='year', keep='last')

income_df = income_df.reset_index(drop=True)
print(income_df)

    year  median_annual_earnings_gbp
0   1999                     14888.0
1   2000                     15800.0
2   2001                     16438.0
3   2002                     16964.0
4   2003                     17508.0
5   2004                     18172.0
6   2005                     18949.0
7   2006                     19521.0
8   2007                     20000.0
9   2008                     20811.0
10  2009                     21310.0
11  2010                     21212.0
12  2012                     21500.0
13  2013                     21837.0
14  2014                     22069.0
15  2015                     22436.0
16  2016                     23084.0
17  2017                     23484.0
18  2018                     24003.0
19  2019                     24937.0
20  2020                     25886.0
21  2021                     25971.0
22  2022                     27774.0
23  2023                     29511.0
24  2024                     31600.0
25  2025                     32890.0

--- TAX GAP DATA CLEANING ---

Step 1: Row 4 is the real header — use it, then re-read from row 5 onwards

In [11]:
taxgap_df = taxgap_raw.copy()
taxgap_df.columns = taxgap_raw.iloc[4]     # set row 4 as column names
taxgap_df = taxgap_df.iloc[5:].reset_index(drop=True)  # drop the header rows

Step 2: Find the "Total tax gap" row

In [12]:
total_row = taxgap_df[taxgap_df['Tax'] == 'Total tax gap']

Step 3: Keep only the year columns (drop 'Tax' and 'Type')

In [13]:
total_row = total_row.drop(columns=['Tax', 'Type'])

Step 4: Transpose so each year becomes a row

In [14]:
taxgap_clean = total_row.T.reset_index()
taxgap_clean.columns = ['tax_year', 'total_tax_gap_bn']

Step 5: Convert "2005-06" → 2006 (use the end year to match income data)

In [15]:
taxgap_clean['year'] = taxgap_clean['tax_year'].str.split('-').str[1].astype(int) + 2000

Step 6: Convert tax gap to float (the "<0.1" entries won't appear in the total row)

In [16]:
taxgap_clean['total_tax_gap_bn'] = pd.to_numeric(
    taxgap_clean['total_tax_gap_bn'], errors='coerce'
)

taxgap_clean = taxgap_clean[['year', 'total_tax_gap_bn']].reset_index(drop=True)
print(taxgap_clean)

    year  total_tax_gap_bn
0   2006              32.5
1   2007              30.4
2   2008              29.5
3   2009              31.6
4   2010              28.6
5   2011              29.6
6   2012              30.1
7   2013              33.1
8   2014              36.5
9   2015              32.8
10  2016              33.0
11  2017              32.7
12  2018              31.9
13  2019              33.3
14  2020              38.5
15  2021              34.2
16  2022              41.8
17  2023              46.4
18  2024              46.8

--- MERGE INTO ONE DATAFRAME ---

In [17]:
# Inner join on year — keeps only the overlapping years (2006–2024)
dashboard_df = pd.merge(income_df, taxgap_clean, on='year', how='inner')

# Calculate year-on-year % changes for both metrics
dashboard_df['income_yoy_pct'] = dashboard_df['median_annual_earnings_gbp'].pct_change() * 100
dashboard_df['taxgap_yoy_pct'] = dashboard_df['total_tax_gap_bn'].pct_change() * 100

dashboard_df = dashboard_df.round(2)
print(dashboard_df)
print(f"\nShape: {dashboard_df.shape}")
print(f"Years covered: {dashboard_df['year'].min()} – {dashboard_df['year'].max()}")

# Export to Desktop
dashboard_df.to_csv('/Users/alexandruvasile/Desktop/dashboard_data.csv', index=False)
print("CSV saved to Desktop!")

    year  median_annual_earnings_gbp  total_tax_gap_bn  income_yoy_pct  \
0   2006                     19521.0              32.5             NaN
1   2007                     20000.0              30.4            2.45
2   2008                     20811.0              29.5            4.06
3   2009                     21310.0              31.6            2.40
4   2010                     21212.0              28.6           -0.46
5   2012                     21500.0              30.1            1.36
6   2013                     21837.0              33.1            1.57
7   2014                     22069.0              36.5            1.06
8   2015                     22436.0              32.8            1.66
9   2016                     23084.0              33.0            2.89
10  2017                     23484.0              32.7            1.73
11  2018                     24003.0              31.9            2.21
12  2019                     24937.0              33.3            3.89
13  2020                     25886.0              38.5            3.81
14  2021                     25971.0              34.2            0.33
15  2022                     27774.0              41.8            6.94
16  2023                     29511.0              46.4            6.25
17  2024                     31600.0              46.8            7.08

    taxgap_yoy_pct
0              NaN
1            -6.46
2            -2.96
3             7.12
4            -9.49
5             5.24
6             9.97
7            10.27
8           -10.14
9             0.61
10           -0.91
11           -2.45
12            4.39
13           15.62
14          -11.17
15           22.22
16           11.00
17            0.86

Shape: (18, 5)
Years covered: 2006 – 2024
CSV saved to Desktop!